export const Command = Object.freeze({
  PING:    "PING",
  ECHO:    "ECHO",
  SET:     "SET",
  GET:     "GET",
  RPUSH:   "RPUSH",
  LPUSH:   "LPUSH",
  LPOP:    "LPOP",
  BLPOP:   "BLPOP",
  LRANGE:  "LRANGE",
  TYPE:    "TYPE",
  XADD:    "XADD",
  XRANGE:  "XRANGE",
  XREAD:   "XREAD",
  INCR:    "INCR",
  MULTI:   "MULTI",
  EXEC:    "EXEC",
  DISCARD: "DISCARD",
});